import { randomUUID } from 'node:crypto';
import { test, expect } from '@playwright/test';

test('SSR signup, protected admin, login and logout', async ({ page, context }) => {
  const email = `cce-e2e-${randomUUID()}@example.com`;
  const password = `CCE-e2e-${randomUUID()}!`;
  await page.goto('/admin');
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('/signup');
  await page.getByLabel('E-posta').fill(email);
  await page.getByLabel('Şifre', { exact: false }).fill(password);
  await page.getByRole('button', { name: 'Kayıt ol' }).click();
  await expect(page).toHaveURL(/\/contributor$/);
  await expect(page.getByText('Oturum ve güncel yetkilerin doğrulandı.')).toBeVisible();
  await page.getByRole('link', { name: 'Karakter taslaklarım ve başvurularım' }).click();
  await page.getByRole('link', { name: 'Yeni taslak', exact: true }).click();
  await page.getByLabel('İsim', { exact: true }).fill('Deniz');
  await page.getByLabel('Kısa tanıtım', { exact: true }).fill('Meraklı bir arşivci.');
  await page.getByLabel('Geçmiş hikâyesi', { exact: true }).fill('Sahil kentinde büyümüş özgün yetişkin karakter.');
  await page.getByLabel('Karakter açıkça yetişkin görünür.').check();
  await page.getByLabel('Gerçek bir kişinin', { exact: false }).check();
  await page.getByRole('button', { name: 'Kaydet ve ön izle' }).click();
  await expect(page).toHaveURL(/\/contributor\/drafts\/[0-9a-f-]+$/);
  await page.getByRole('button', { name: 'İncelemeye gönder' }).click();
  await expect(page.getByText('SUBMITTED', { exact: true })).toBeVisible();
  await expect(page.getByLabel('İsim', { exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Başvuruyu geri çek' }).click();
  await expect(page.getByText('WITHDRAWN', { exact: true })).toBeVisible();
  await page.goto('/contributor');
  const response = await page.reload();
  expect(response?.headers()['cache-control']).toContain('no-store');
  const cookies = await context.cookies();
  expect(cookies.some(cookie => cookie.name.startsWith('sb-'))).toBeTruthy();
  await page.goto('/admin');
  await expect(page).toHaveURL(/\/contributor$/);
  await page.getByRole('button', { name: 'Çıkış yap' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('/contributor');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('E-posta').fill(email);
  await page.getByLabel('Şifre', { exact: false }).fill(password);
  await page.getByRole('button', { name: 'Giriş yap' }).click();
  await expect(page).toHaveURL(/\/contributor$/);
  await page.getByRole('button', { name: 'Çıkış yap' }).click();
  await expect(page).toHaveURL(/\/login$/);
});
